package main

import (
	"fmt"

	"github.com/spf13/cobra"
)

func newUseCmd() *cobra.Command {
	return &cobra.Command{
		Use:   "use <name>",
		Short: "Switch the active profile in the current shell (requires shell integration)",
		Long: `Switch the active profile in the current shell by exporting CLAUDE_CONFIG_DIR.

This subcommand is normally handled by the shell function generated by
` + "`claude-profile init <shell>`" + `. If you see this error message, the
shell integration is not loaded.`,
		Args: cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			return fmt.Errorf("`use` requires shell integration. Activate it: eval \"$(claude-profile init <shell>)\"")
		},
	}
}
