package shell

import (
	"fmt"
	"strings"

	"github.com/dmitriipyshinskii/claude-profile/internal/profile"
)

func Generate(shell string, profiles []profile.Profile) (string, error) {
	var b strings.Builder
	switch shell {
	case "zsh", "bash":
		fmt.Fprintf(&b, "# Generated by claude-profile shell-init %s\n", shell)
		for _, p := range profiles {
			fmt.Fprintf(&b, "alias claude-%s='CLAUDE_CONFIG_DIR=%s claude'\n", p.Name, p.Path)
		}
	case "fish":
		fmt.Fprintf(&b, "# Generated by claude-profile shell-init fish\n")
		for _, p := range profiles {
			fmt.Fprintf(&b, "alias claude-%s \"CLAUDE_CONFIG_DIR=%s claude\"\n", p.Name, p.Path)
		}
	default:
		return "", fmt.Errorf("unknown shell: %s (supported: zsh, bash, fish)", shell)
	}
	return b.String(), nil
}
