package shell

import (
	"fmt"
	"strings"

	"github.com/dmitriipyshinskii/claude-profile/internal/profile"
)

func Generate(shell string, profiles []profile.Profile) (string, error) {
	var b strings.Builder
	switch shell {
	case "zsh", "bash":
		fmt.Fprintf(&b, "# Generated by claude-profile init %s\n", shell)
		for _, p := range profiles {
			fmt.Fprintf(&b, "alias claude-%s='CLAUDE_CONFIG_DIR=%s claude'\n", p.Name, p.Path)
		}
		fmt.Fprint(&b, posixUseFunction)
	case "fish":
		fmt.Fprint(&b, "# Generated by claude-profile init fish\n")
		for _, p := range profiles {
			fmt.Fprintf(&b, "alias claude-%s \"CLAUDE_CONFIG_DIR=%s claude\"\n", p.Name, p.Path)
		}
		fmt.Fprint(&b, fishUseFunction)
	default:
		return "", fmt.Errorf("unknown shell: %s (supported: zsh, bash, fish)", shell)
	}
	return b.String(), nil
}

const posixUseFunction = `
claude-profile() {
    if [ "$1" = "use" ]; then
        if [ -z "$2" ]; then
            echo "usage: claude-profile use <name>" >&2
            return 2
        fi
        local _path
        _path=$(command claude-profile which "$2") || return $?
        if [ ! -d "$_path" ]; then
            echo "claude-profile: profile '$2' not found at $_path" >&2
            return 1
        fi
        export CLAUDE_CONFIG_DIR="$_path"
    else
        command claude-profile "$@"
    fi
}
`

const fishUseFunction = `
function claude-profile
    if test "$argv[1]" = "use"
        if test (count $argv) -lt 2
            echo "usage: claude-profile use <name>" >&2
            return 2
        end
        set -l _path (command claude-profile which $argv[2]); or return $status
        if not test -d "$_path"
            echo "claude-profile: profile '$argv[2]' not found at $_path" >&2
            return 1
        end
        set -gx CLAUDE_CONFIG_DIR $_path
    else
        command claude-profile $argv
    end
end
`
